# Generated by Django 3.2.7 on 2021-09-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zipCode', models.CharField(max_length=5)),
                ('photo_url', models.TextField()),
                ('description', models.CharField(max_length=280)),
                ('resturaunt', models.BooleanField()),
                ('shopping', models.BooleanField()),
                ('social', models.BooleanField()),
            ],
        ),
    ]
