# Generated by Django 3.2.7 on 2021-09-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenward', '0003_local_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='resturaunt',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='local',
            name='shopping',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='local',
            name='social',
            field=models.NullBooleanField(),
        ),
    ]
