# Generated by Django 3.2.7 on 2021-09-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenward', '0004_auto_20210911_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='resturaunt',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='shopping',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='social',
            field=models.BooleanField(null=True),
        ),
    ]
